apiVersion: v1
kind: Service
metadata:
  name: parallel-orchestrator-service
spec:
  selector:
    app: parallel-orchestrator
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8061
  type: LoadBalancer